spring:
  application:
    name: product-service
  threads:
    virtual:
      enabled: true
  mongodb:
    # uri: mongodb://root:password@localhost:27017/product-db?authSource=admin
    #  uri: product-db
    # Sintaxis: ${NOMBRE_VAR_ENTORNO : VALOR_POR_DEFECTO}
    host: ${MONGO_HOST:localhost}
    port: ${MONGO_PORT:27017}
    database: ${MONGO_DATABASE:product-db}
    username: ${MONGO_USERNAME}
    password: ${MONGO_PASSWORD}
    authentication-database: ${MONGO_AUTH_DB:admin}
  web:
    error:
      include-stacktrace: never
      include-message: always

server:
  port: ${SERVER_PORT:8080}
